# Unit 3 - Advanced Python - NumPy - Assingment #1  

## 1. Environment Set up

In [ ]:
import numpy as np

In [ ]:
#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])

In [15]:
print(np_olympic_country)
print(np_olympic_country_Gold)
print(np_olympic_country_Silver)
print(np_olympic_country_Bronze)

['GBR' 'China' 'RUS' 'US' 'KOR' 'JPN' 'GER']
[29 38 24 46 13  7 11]
[17 28 25 28  8 14 11]
[19 22 32 29  7 17 14]


## 2.	Find country with maximum gold

In [27]:
# 1. First way
max_gold_index = np.where(np_olympic_country_Gold == np_olympic_country_Gold.max())
print(np_olympic_country[max_gold_index])

['US']


In [26]:
# 2. Second way
print(np_olympic_country[np.where(np_olympic_country_Gold == np_olympic_country_Gold.max())])

['US']


## 3.	Find countries with more than 20 gold medals

In [25]:
# 1. First way
indexes = np.where(np_olympic_country_Gold >= 20)
country_list = np_olympic_country[indexes]
print(country_list)

['GBR' 'China' 'RUS' 'US']


In [24]:
# 2. Second way
print(np_olympic_country[np.where(np_olympic_country_Gold >= 20)])

['GBR' 'China' 'RUS' 'US']
